services:
  smtp-service-server:
    image: makwanagautam/smtp-service-server:v1
    container_name: smtp-service-server
    environment:
      - PORT=5001
    expose:
      - "5001:5001"
    networks:
      - smtp-service-server
    env_file: .env
    restart: unless-stopped

networks:
  smtp-service-server:
    driver: bridge
