services:
  mongoserver:
    image: mongo
    container_name: mongodb-server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ~/mongo/data:/data/db
    networks:
      - smtp-service-server

  redisserver:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - smtp-service-server

  backend1:
    image: makwanagautam/smtp-service-server:v1
    container_name: backend1
    environment:
      - PORT=5513
    expose:
      - "5513"
    networks:
      - smtp-service-server
    depends_on:
      - mongoserver
      - redisserver
    env_file: .env

networks:
  smtp-service-server:
    driver: bridge
